### ISSUE TITLE
Master Progress Tracker for CRAN Complete Submission

### ISSUE THREAD

**Issue by aaronrudkin** [DeclareDesign/fabricatr#28]
This is a roadmap to CRAN submission.

**Feature Additions**
- [x] Passthrough resampling (#25 and #27)
    - [x] syntax
    - [x] vignette
    - [x] manual documentation
    - [x] tests
    - [x] merge feature branch
- [x] Additional data types for variable creation? Overdispersed count data? Zero inflated count data (we can already do this by doing a binary first stage and then a count stage and then merging in place -- should we make this easier?) Time series data?
- [x] Fabricate refactor - allow partially or non-nested data (#23)
    - [x] add_level
    - [x] nest_level
    - [x] modify_level
    - [x] tests

**Testing and Test Coverage**
- [x] Fabricate (dummy item pending rewrite)
- [x] Fabricatr does not depend on other packages, but we should ensure fabricatr is running in the test matrix for the other packages

**Getting Started Vignette**
- [x] Rewrite
- [x] Examples with new syntax
- [x] Reduce dependence on examples that don't make substantive sense
- [x] Front page example

**CRAN Submission Prep**
- [x] Look up any checks needed besides the default R build/check process
   - [x] WinBuilder
- [x] Confirm licenses, copyright statements, and other submission metadata
- [x] Submit

**Comment by nfultz** [comment]
re ZI data - I usually write that in base R as ```rbinom(10,1, .5) * rpois(10, 3)``` so I don't see a huge benefit in a helper function but it would also be super easy.
